Домашнее задание для java-collections-stream
Kenzanter/hh-school-2024-java-collections-stream pull request #1
Opened 2024-12-15 15:58 UTC by Kenzanter

Добавлено решение задач с 1 по 8.
Проведен рефакторинг задачи 9.

2024-12-16 21:01 UTC, genroelgvozo requested changes

2024-12-16 21:01 UTC, genroelgvozo commented on src/main/java/tasks/Task6.java
> +            .map(regionId -> person.firstName() + " - " + areaMap.get(regionId).getName())
по скорости все ок
идеологически лучше склейку в строку выносить в метод - его проще править отдельно, вдруг надо другой формат. И правильно что мапу сразу на арейку целиком - метод ее пускай принимает и сам решает какие поля ему нужны
Остальное гуд

2024-12-16 21:01 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +                .filter(resume -> Objects.equals(resume.personId(), person.id()))
долго) бегаешь для каждой персоны по всем резюме, надо как-то сходу вынимать нужные (у тебя уже были идеи в пред задачках, просто чуть сложнее тут)

2024-12-16 21:01 UTC, genroelgvozo commented on src/main/java/tasks/Task9.java
> +    // Переменная count не нужна
Чем плохо было наличие, кроме того что не нужна?)

2024-12-16 21:01 UTC, genroelgvozo commented on src/main/java/tasks/Task9.java
> +    // В итоге, для нашего случая, получается что мы сравниваем два одинаковых отсортированных набора чисел.
все верно, единственное что это работает если бакетов больше чем чисел (и тут конструктор сразу создаст их больше) и главное что больше чем максимальное число (они даже не должны быть строго возрастать на 1, главное два условия)

если ты засунешь 1,2,16,36 в пустую мапу в которой 16 бакетов по-умолчанию, то все сломается)

2024-12-17 06:07 UTC, Kenzanter commented on src/main/java/tasks/Task9.java
> +    // Переменная count не нужна
Если Stream будет параллельным, то операция count++ может давать неправильный результат

2024-12-17 07:16 UTC, Kenzanter commented on src/main/java/tasks/Task6.java
> +            .map(regionId -> person.firstName() + " - " + areaMap.get(regionId).getName())
Понял. Переделал, вынес склейку в отдельный метод

2024-12-17 07:19 UTC, Kenzanter commented on src/main/java/tasks/Task8.java
> +                .filter(resume -> Objects.equals(resume.personId(), person.id()))
Хотел сразу сделать при помощи Map, но не получалось сделать при помощи метода Collectors.toMap. Нашел метод Collectors.groupingBy, с ним все получилось) Переделал, заменил Set на Map

2024-12-17 07:29 UTC, Kenzanter commented on src/main/java/tasks/Task9.java
> +    // В итоге, для нашего случая, получается что мы сравниваем два одинаковых отсортированных набора чисел.
Да, это я понимаю) Если число будет больше чем емкость, то оно может попасть, к примеру, в бакет в середине или в бакет к другому числу. И тогда при сравнении отсортированного порядка может не получиться

2024-12-19 14:40 UTC, genroelgvozo commented on src/main/java/tasks/Task9.java
> +    // В итоге, для нашего случая, получается что мы сравниваем два одинаковых отсортированных набора чисел.
ну ты может и понимаешь, но я то не знаю, а ты не уточнил нюанс) но ок

2024-12-21 14:59 UTC, merged